// Package hooks defines the Claude Code hook event types and the settings-file
// schema used to configure which hooks fire for which events.
package hooks

import "encoding/json"

// EventName identifies a Claude Code lifecycle hook event.
type EventName string

const (
	EventSessionStart   EventName = "SessionStart"
	EventSessionEnd     EventName = "SessionEnd"
	EventStop           EventName = "Stop"
	EventSubagentStart  EventName = "SubagentStart"
	EventSubagentStop   EventName = "SubagentStop"
	EventStopFailure    EventName = "StopFailure"
	EventPreToolUse     EventName = "PreToolUse"
	EventPostToolUse    EventName = "PostToolUse"
	EventWorktreeCreate EventName = "WorktreeCreate"
	EventWorktreeRemove EventName = "WorktreeRemove"
	// EventUserPromptSubmit fires before each user message is sent to the model.
	// Per the real Claude Code contract the hook CANNOT replace the prompt: it
	// may only append "additionalContext" (inside hookSpecificOutput), or block
	// the prompt via {"decision":"block","reason":...} / exit 2. There is no
	// "userPrompt"/"updatedPrompt" field (that is an open upstream feature
	// request, anthropics/claude-code#27365). If the hook outputs nothing, the
	// original prompt is forwarded unchanged.
	// sr:docs https://code.claude.com/docs/en/hooks#userpromptsubmit
	EventUserPromptSubmit EventName = "UserPromptSubmit"
)

// Input is the JSON payload sent to a hook handler via stdin (command hooks)
// or POST body (HTTP hooks). Fields are populated per event type.
type Input struct {
	SessionID      string    `json:"session_id"`
	TranscriptPath string    `json:"transcript_path,omitempty"`
	Cwd            string    `json:"cwd"`
	HookEventName  EventName `json:"hook_event_name"`
	PermissionMode string    `json:"permission_mode,omitempty"`

	// SessionStart / SessionEnd
	// Source is the SessionStart field in the real Claude Code payload:
	// "startup" | "resume" | "clear" | "compact" — compaction (auto or manual) uses
	// "compact". Verified empirically against claude 2.x: the SessionStart hook
	// stdin carries "source" (NOT "trigger"). Also reused by SessionEnd
	// ("prompt_input_exit"). The mock sets it to "startup"/"resume"/(override).
	// sr:docs https://code.claude.com/docs/en/hooks#sessionstart
	Source string `json:"source,omitempty"`
	Model  string `json:"model,omitempty"`

	// UserPromptSubmit
	// Prompt is the raw text of the user message being submitted. The real Claude
	// Code payload names this field "prompt" (NOT "user_prompt").
	// sr:docs https://code.claude.com/docs/en/hooks#userpromptsubmit
	Prompt string `json:"prompt,omitempty"`

	// Stop / SubagentStop / StopFailure
	StopReason string `json:"stop_reason,omitempty"`
	// StopHookActive is true when this Stop/SubagentStop fire is a CONTINUATION of
	// a prior block (the hook's own block re-ran the turn, which fires the hook
	// again). Hooks check it to break their own infinite loop — the real Claude
	// contract. The mock sets it on every re-fire after the first block.
	// sr:docs https://code.claude.com/docs/en/hooks#stop
	StopHookActive bool `json:"stop_hook_active,omitempty"`

	// PreToolUse / PostToolUse
	ToolName   string          `json:"tool_name,omitempty"`
	ToolInput  json.RawMessage `json:"tool_input,omitempty"`
	ToolOutput json.RawMessage `json:"tool_output,omitempty"`

	// SubagentStart / SubagentStop — agent type name (matcher for these events)
	AgentType string `json:"agent_type,omitempty"`
	// SubagentStart / SubagentStop — unique per-subagent id generated by the parent
	// when it spawns a subagent via the Agent (alias Task) tool. The real Claude
	// hook payload carries this so the SubagentStart and matching SubagentStop can
	// be correlated.
	// sr:docs https://code.claude.com/docs/en/hooks#subagentstart
	AgentID string `json:"agent_id,omitempty"`
	// SubagentStop — path to the subagent's OWN transcript file
	// (<session>/subagents/agent-<agent_id>.jsonl). The real Claude Code SubagentStop
	// payload carries this documented field so hooks can read the dispatch prompt
	// (with --task-id) directly without deriving the path from transcript_path.
	// sr:docs https://code.claude.com/docs/en/hooks#subagentstop
	AgentTranscriptPath string `json:"agent_transcript_path,omitempty"`

	// WorktreeCreate / WorktreeRemove
	WorktreeName string `json:"worktree_name,omitempty"`
}

// Output is the JSON response a hook handler may write to stdout.
// All fields are optional; unset fields have no effect.
type Output struct {
	Continue      *bool  `json:"continue,omitempty"`
	StopReason    string `json:"stopReason,omitempty"`
	SystemMessage string `json:"systemMessage,omitempty"`
	// Decision / Reason are the documented Stop / UserPromptSubmit block controls.
	// Decision "block" + Reason keeps the agent working (Stop) or rejects the
	// prompt (UserPromptSubmit). For PreToolUse these top-level fields are
	// DEPRECATED — use HookSpecificOutput.PermissionDecision instead.
	// sr:docs https://code.claude.com/docs/en/hooks#stop
	Decision string `json:"decision,omitempty"`
	Reason   string `json:"reason,omitempty"`

	HookSpecificOutput *HookSpecificOutput `json:"hookSpecificOutput,omitempty"`
}

// HookSpecificOutput carries event-specific control fields inside Output.
type HookSpecificOutput struct {
	HookEventName            EventName       `json:"hookEventName,omitempty"`
	AdditionalContext        string          `json:"additionalContext,omitempty"`
	PermissionDecision       string          `json:"permissionDecision,omitempty"`
	PermissionDecisionReason string          `json:"permissionDecisionReason,omitempty"`
	UpdatedInput             json.RawMessage `json:"updatedInput,omitempty"`
	UpdatedToolOutput        string          `json:"updatedToolOutput,omitempty"`
	WorktreePath             string          `json:"worktreePath,omitempty"`
}
