// Package hooks defines the Claude Code hook event types and the settings-file
// schema used to configure which hooks fire for which events.
package hooks

import (
	"encoding/json"
)

// EventName identifies a Claude Code lifecycle hook event.
type EventName string

const (
	EventSessionStart  EventName = "SessionStart"
	EventSessionEnd    EventName = "SessionEnd"
	EventStop          EventName = "Stop"
	EventSubagentStart EventName = "SubagentStart"
	EventSubagentStop  EventName = "SubagentStop"
	EventStopFailure   EventName = "StopFailure"
	EventPreToolUse    EventName = "PreToolUse"
	EventPostToolUse   EventName = "PostToolUse"
	// EventPostToolUseFailure fires instead of PostToolUse when a tool that ran
	// failed (claude 2.1.282: a failing foreground Bash fired it, with error).
	// sr:docs https://code.claude.com/docs/en/hooks#posttoolusefailure
	EventPostToolUseFailure EventName = "PostToolUseFailure"
	EventWorktreeCreate     EventName = "WorktreeCreate"
	EventWorktreeRemove     EventName = "WorktreeRemove"
	// EventPreCompact / EventPostCompact bracket a compaction. PreCompact can
	// block it (exit 2 or decision:block); PostCompact receives the summary.
	// sr:docs https://code.claude.com/docs/en/hooks#precompact
	// sr:docs https://code.claude.com/docs/en/hooks#postcompact
	EventPreCompact  EventName = "PreCompact"
	EventPostCompact EventName = "PostCompact"
	// EventUserPromptSubmit fires before each user message is sent to the model.
	// Per the real Claude Code contract the hook CANNOT replace the prompt: it
	// may only append "additionalContext" (inside hookSpecificOutput), or block
	// the prompt via {"decision":"block","reason":...} / exit 2. There is no
	// "userPrompt"/"updatedPrompt" field (that is an open upstream feature
	// request, anthropics/claude-code#27365). If the hook outputs nothing, the
	// original prompt is forwarded unchanged.
	// sr:docs https://code.claude.com/docs/en/hooks#userpromptsubmit
	EventUserPromptSubmit EventName = "UserPromptSubmit"
)

// Input is the JSON payload sent to a hook handler via stdin (command hooks)
// or POST body (HTTP hooks). Fields are populated per event type.
type Input struct {
	SessionID      string `json:"session_id"`
	TranscriptPath string `json:"transcript_path,omitempty"`
	Cwd            string `json:"cwd"`
	// PromptID names the user prompt the event belongs to: every event after the
	// first UserPromptSubmit carries it (SessionStart before any prompt does not),
	// and each prompt has its own (recorded: snapshots/runs/forkresume, compact).
	PromptID string `json:"prompt_id,omitempty"`
	// ContinuesPrompt: a UserPromptSubmit that does not begin a prompt (a task
	// notification handed to the model, recorded in snapshots/runs/midturn).
	ContinuesPrompt bool `json:"-"`
	// PermissionMode is the mode the session runs in, on the events that are about
	// a turn (UserPromptSubmit, tool calls, Stop, SubagentStop), not on the
	// session's and sub-agent's own start and end (recorded: snapshots/runs/bgagent).
	PermissionMode string `json:"permission_mode,omitempty"`
	// AgentType is the sub-agent's type name (the matcher for SubagentStart and
	// SubagentStop). AgentID is its unique id, generated by the parent when it
	// spawns a subagent via the Agent (alias Task) tool: the real Claude hook
	// payload carries it so the SubagentStart and matching SubagentStop can be
	// correlated. Both come before hook_event_name, as recorded.
	// sr:docs https://code.claude.com/docs/en/hooks#subagentstart
	AgentID       string    `json:"agent_id,omitempty"`
	AgentType     string    `json:"agent_type,omitempty"`
	HookEventName EventName `json:"hook_event_name"`
	SessionTitle  string    `json:"session_title,omitempty"` // a named session's resume start (snapshots/runs/resume-name)

	// SessionStart: Source is "startup" | "resume" | "clear" | "compact" |
	// "fork". Verified against claude 2.1.282: a `--resume <id> --fork-session`
	// run fires SessionStart with source "fork" (docs: SessionStart input).
	// sr:docs https://code.claude.com/docs/en/hooks#sessionstart
	Source string `json:"source,omitempty"`
	// ResumeFields are a resumed session's: what the resume costs and how stale it is.
	*ResumeFields
	Model string `json:"model,omitempty"`

	// SessionEnd: Reason is why the session ended. A `claude -p` run ends with
	// reason "other" (recorded in claude-mock/snapshots/runs: the SessionEnd payloads of runs such as resume-unknown).
	// sr:docs https://code.claude.com/docs/en/hooks#sessionend
	Reason string `json:"reason,omitempty"`

	// UserPromptSubmit
	// Prompt is the raw text of the user message being submitted. The real Claude
	// Code payload names this field "prompt" (NOT "user_prompt").
	// sr:docs https://code.claude.com/docs/en/hooks#userpromptsubmit
	Prompt string `json:"prompt,omitempty"`

	// Stop / SubagentStop. Real Claude Code sends stop_hook_active (false
	// included), last_assistant_message, background_tasks and session_crons on
	// both — pointers here so they are present exactly on those events.
	// sr:docs https://code.claude.com/docs/en/hooks#stop-input
	StopHookActive *bool `json:"stop_hook_active,omitempty"`
	// SubagentStop — (written between stop_hook_active and last_assistant_message) path to the subagent's OWN transcript file
	// (<session>/subagents/agent-<agent_id>.jsonl). The real Claude Code SubagentStop
	// payload carries this documented field so hooks can read the dispatch prompt
	// (with --task-id) directly without deriving the path from transcript_path.
	// sr:docs https://code.claude.com/docs/en/hooks#subagentstop
	AgentTranscriptPath  string            `json:"agent_transcript_path,omitempty"`
	LastAssistantMessage *string           `json:"last_assistant_message,omitempty"`
	BackgroundTasks      *[]BackgroundTask `json:"background_tasks,omitempty"`
	SessionCrons         *[]any            `json:"session_crons,omitempty"`

	// PreToolUse / PostToolUse, in the order the real payload writes them:
	// tool_name, tool_input, tool_response, tool_use_id.
	ToolName  string          `json:"tool_name,omitempty"`
	ToolInput json.RawMessage `json:"tool_input,omitempty"`
	// ToolResponse is PostToolUse's tool_response: the tool's structured
	// result where it has one (Bash: {stdout, stderr, interrupted, …}), else
	// the text the model got.
	// sr:docs https://code.claude.com/docs/en/hooks#posttooluse-input
	ToolResponse json.RawMessage `json:"tool_response,omitempty"`
	// ToolUseID is the id of the tool_use block the event is about. Real Claude
	// Code sends it on PreToolUse and PostToolUse, and records it as the
	// toolUseID of the hook's attachment.
	// sr:docs https://code.claude.com/docs/en/hooks#pretooluse-input
	ToolUseID string `json:"tool_use_id,omitempty"`
	// PostToolUseFailure: error is the text the model got, is_interrupt
	// whether the user interrupted it. Both carry duration_ms, the tool's run
	// time, as PostToolUse does (claude 2.1.282 payloads).
	Error       string `json:"error,omitempty"`
	IsInterrupt *bool  `json:"is_interrupt,omitempty"`
	DurationMs  *int64 `json:"duration_ms,omitempty"`

	// WorktreeCreate carries the new worktree's slug as `name` (recorded:
	// snapshots/runs/worktree-hooks), WorktreeRemove the directory as `worktree_path`.
	// sr:docs https://code.claude.com/docs/en/hooks#worktreecreate-input
	WorktreeName string `json:"name,omitempty"`
	WorktreePath string `json:"worktree_path,omitempty"`

	// PreCompact / PostCompact: what triggered the compaction ("manual" |
	// "auto"); PreCompact's custom_instructions (null unless a manual /compact
	// passed some), PostCompact's compact_summary.
	// sr:docs https://code.claude.com/docs/en/hooks#precompact-input
	Trigger            string          `json:"trigger,omitempty"`
	CustomInstructions json.RawMessage `json:"custom_instructions,omitempty"`
	CompactSummary     *string         `json:"compact_summary,omitempty"`
}
