package runner

import (
	"context"
	"encoding/json"
	"errors"
	"strings"

	"github.com/sloprail/harness-mocks/claude-mock/internal/hooks"
)

// compactSummary is a compaction's summary record: the scenario's own
// isCompactSummary record, or one built from the control record. Its uuid is
// minted up front, since the boundary names it as anchor, and it chains to the
// boundary. ok is false when the scenario's own record is not a JSON object.
func compactSummary(rec *cliRecord, line []byte) (sum map[string]any, anchor, text string, ok bool) {
	if rec.IsCompactSummary {
		if json.Unmarshal(line, &sum) != nil {
			return nil, "", "", false
		}
	} else {
		body := rec.Summary
		if body == "" {
			body = "This session is being continued from a previous conversation that ran out of context."
		}
		sum = map[string]any{
			"type": "user", "isCompactSummary": true,
			"message": map[string]any{"role": "user", "content": body},
		}
		if rec.ID != "" {
			sum["id"] = rec.ID
		}
	}
	if _, has := sum["isVisibleInTranscriptOnly"]; !has {
		sum["isVisibleInTranscriptOnly"] = true // every one of the 66 real summaries
	}
	anchor, _ = sum["uuid"].(string)
	if anchor == "" {
		anchor = newRecordUUID()
		sum["uuid"] = anchor
	}
	chainsFromPrevious(sum) // chains to the boundary
	if m, isMap := sum["message"].(map[string]any); isMap {
		text, _ = m["content"].(string)
	}
	return sum, anchor, text, true
}

// fireSummarizerStop fires SubagentStop for the summarizer that wrote a manual
// compaction's summary: agent_type "", a fresh agent_id, an agent_transcript_path
// no file is ever written to, and the summary as last_assistant_message.
func fireSummarizerStop(ctx context.Context, cfg Config, inv *hooks.Invoker, tr *transcript, summaryText string) {
	summarizer, err := newAgentID()
	if err != nil {
		return
	}
	active := false
	tasks := cfg.bg.running()
	crons := sessionCrons(cfg.wake)
	sessionFile := cfg.sessionFile
	if sessionFile == "" {
		sessionFile = tr.path
	}
	_, _ = inv.WithRecorder(nil).Fire(ctx, hooks.Input{
		SessionID: cfg.SessionID, Cwd: cfg.Cwd, HookEventName: hooks.EventSubagentStop,
		AgentID: summarizer, AgentType: "", StopHookActive: &active,
		AgentTranscriptPath:  claudeSubagentLayout.Path(sessionFile, summarizer),
		LastAssistantMessage: &summaryText, BackgroundTasks: &tasks, SessionCrons: &crons,
	})
}

// writeCompactCommand writes the three records the /compact command leaves after
// a manual compaction: the caveat, the command, and its output "Compacted <what
// the Pre/PostCompact hooks reported>".
func writeCompactCommand(cfg Config, tr *transcript, preRuns, postRuns []hooks.HandlerRun) {
	lines := append(compactHookLines("PreCompact", preRuns), compactHookLines("PostCompact", postRuns)...)
	tr.persistMap(map[string]any{"type": "user", "isMeta": true, "message": map[string]any{"role": "user",
		"content": "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"}})
	tr.persistMap(map[string]any{"type": "user", "message": map[string]any{"role": "user",
		"content": "<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>"}})
	stdout := "<local-command-stdout>Compacted " + strings.Join(lines, "\n") + "</local-command-stdout>"
	tr.persistMap(map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": stdout}})
	writeFrame(cfg, map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": stdout}, "isReplay": true})
	tr.flushHookRuns()
}

// compactBlockMessage is what a PreCompact block tells the user: the blocking
// handler's reason or stderr, else the decision's reason.
func compactBlockMessage(out hooks.Output, err error) string {
	var be *hooks.BlockError
	if errors.As(err, &be) {
		if be.Reason != "" {
			return be.Reason
		}
		return strings.TrimSpace(be.Stderr)
	}
	return strings.TrimSpace(out.Reason)
}
