package e2e

// notReplaying are the recorded runs whose replay is not green yet, and why.
// The list only shrinks: an entry whose run is gone, or whose run now replays
// green, fails TestGeneratedReplay. "adapter:" is something of the recording
// the claude adapter cannot reproduce yet; "untriaged:" is a replay that
// differs and has not been looked at (the mock, the adapter or the recording
// may be wrong).
var notReplaying = map[string]string{
	"agent-invalid-description":   "untriaged: the replay differs from the recording (event stream: recording 6, mock 6, hook payloads: recording 4, mock 4)",
	"agent-invalid-input":         "untriaged: the replay differs from the recording (event stream: recording 6, mock 6, hook payloads: recording 4, mock 4)",
	"all-hooks":                   "untriaged: the replay differs from the recording (event stream: recording 4, mock 4, hook payloads: recording 3, mock 3)",
	"all-hooks-slow-first":        "untriaged: the replay differs from the recording (event stream: recording 4, mock 4, hook payloads: recording 3, mock 3)",
	"bashfail":                    "untriaged: the replay differs from the recording (event stream: recording 8, mock 8, hook payloads: recording 8, mock 8)",
	"bgagent":                     "untriaged: the replay differs from the recording (event stream: recording 19, mock 15, hook payloads: recording 12, mock 12)",
	"bgagent-concurrent-limit":    "adapter: the setup has env, which the adapter does not install",
	"bgagent-definition":          "adapter: the setup has prepare.sh, which the adapter does not install",
	"bgagent-nested-launcher":     "untriaged: the replay differs from the recording (event stream: recording 26, mock 18, hook payloads: recording 16, mock 16)",
	"bgbash":                      "untriaged: the replay differs from the recording (event stream: recording 11, mock 11, hook payloads: recording 6, mock 6)",
	"cap":                         "untriaged: the replay differs from the recording (event stream: recording 24, mock 12, hook payloads: recording 12, mock 12)",
	"cap-sub":                     "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 16, mock 16)",
	"compact":                     "adapter: the setup has args, which the adapter does not install",
	"compact-nohooks":             "adapter: the setup has args, which the adapter does not install",
	"ctxmulti":                    "untriaged: the replay differs from the recording (event stream: recording 4, mock 4, hook payloads: recording 4, mock 4)",
	"fg-subagent-bash":            "untriaged: the replay differs from the recording (event stream: recording 18, mock 14, hook payloads: recording 10, mock 10)",
	"fgsub-maxturns":              "adapter: the setup has prepare.sh, which the adapter does not install",
	"fgsub-report-scan":           "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 8, mock 8)",
	"fgsub-report-scan-assistant": "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 8, mock 8)",
	"fgsub-report-scan-perm":      "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 8, mock 8)",
	"fgsub-report-scan-role":      "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 8, mock 8)",
	"fgsub-tool-stats":            "adapter: sub-agent: the model called Write: the adapter maps Bash and Agent",
	"file-tools":                  "adapter: the setup has args, which the adapter does not install",
	"forkresume":                  "adapter: the setup has args, which the adapter does not install",
	"hook-exit-codes":             "adapter: the model called Read: the adapter maps Bash and Agent",
	"hook-exit-json":              "untriaged: the replay differs from the recording (event stream: recording 25, mock 25, hook payloads: recording 26, mock 26)",
	"hook-timeout":                "untriaged: the replay differs from the recording (event stream: recording 6, mock 4, hook payloads: recording 1, mock 1)",
	"hook-unstartable":            "untriaged: the replay differs from the recording (event stream: recording 4, mock 4)",
	"hookerrors":                  "untriaged: the replay differs from the recording (event stream: recording 11, mock 10, hook payloads: recording 8, mock 8)",
	"hookmix":                     "adapter: sub-agent: the model called Read: the adapter maps Bash and Agent",
	"http-hook":                   "untriaged: the replay differs from the recording (event stream: recording 4, mock 4, hook payloads: recording 1, mock 1)",
	"isolated-worktree":           "untriaged: the replay differs from the recording (event stream: recording 19, mock 9, hook payloads: recording 14, mock 14)",
	"matcher":                     "adapter: the model called Read: the adapter maps Bash and Agent",
	"meta":                        "untriaged: the replay differs from the recording (event stream: recording 22, mock 17, hook payloads: recording 16, mock 16)",
	"midturn":                     "untriaged: the replay differs from the recording (event stream: recording 13, mock 13, hook payloads: recording 9, mock 9)",
	"nested-fork-limit":           "adapter: the setup has env, which the adapter does not install",
	"nested-session-env":          "adapter: the setup has env, which the adapter does not install",
	"no-session-persistence":      "adapter: the setup has args, which the adapter does not install",
	"plugin-hooks":                "adapter: the setup has prepare.sh, which the adapter does not install",
	"prompt-blocked":              "untriaged: the replay differs from the recording (event stream: recording 2, mock 2, hook payloads: recording 1, mock 1)",
	"prompt-blocked-json":         "untriaged: the replay differs from the recording (event stream: recording 2, mock 2, hook payloads: recording 1, mock 1)",
	"prompt-blocked-suppressed":   "untriaged: the replay differs from the recording (event stream: recording 2, mock 2, hook payloads: recording 1, mock 1)",
	"resume-continue":             "adapter: the setup has args, which the adapter does not install",
	"resume-continue-fork":        "adapter: the setup has args, which the adapter does not install",
	"resume-continue-none":        "adapter: the setup has args, which the adapter does not install",
	"resume-name":                 "adapter: the setup has args, which the adapter does not install",
	"resume-path":                 "adapter: the setup has args, which the adapter does not install",
	"resume-unknown":              "adapter: the setup has args, which the adapter does not install",
	"schedule-wakeup-limits":      "adapter: the model called ScheduleWakeup: the adapter maps Bash and Agent",
	"stops":                       "untriaged: the replay differs from the recording (event stream: recording 15, mock 14, hook payloads: recording 10, mock 10)",
	"subprocess-session-env":      "untriaged: the replay differs from the recording (event stream: recording 6, mock 6, hook payloads: recording 8, mock 8)",
	"symlinked-cwd":               "adapter: the setup has cwd, which the adapter does not install",
	"tool-errors":                 "adapter: the model called Read: the adapter maps Bash and Agent",
	"tool-invalid-input":          "adapter: the model called Read: the adapter maps Bash and Agent",
	"transcript-at-start":         "untriaged: the replay differs from the recording (event stream: recording 4, mock 4, hook payloads: recording 4, mock 4)",
	"transcript-retention":        "adapter: the setup has prepare.sh, which the adapter does not install",
	"worktree-hooks":              "untriaged: the replay differs from the recording (event stream: recording 10, mock 9, hook payloads: recording 9, mock 9)",
}
